---
title: "2. Summary statistics"
output: rmarkdown::github_document
---

```{r message=FALSE}
library(gtsummary)
```

```{r}
df <- read.csv("data/csv/DIG.csv")
```

```{r}
head(df)
```
```{r}
colnames(df)
```

```{r}
nrow(df)
```

```{r}
length(unique(df$ID))
```

```{r}
df %>% 
  select(TRTMT, AGE, EJF_PER, CHFDUR, SEX, RACE, EJFMETH, NSYM, PREVMI, ANGINA, DIABETES, HYPERTEN, DIGUSE, CHFETIOL, DIURETK, DIURET, ACEINHIB, NITRATES, VASOD, DIGDOSE) %>% 
  tbl_summary(by = TRTMT)
```

You can customize the output.

```{r}
df2 <- df %>% 
  mutate(TRTMT = if_else(TRTMT==1, "DIGOXIN", "PLACEBO"), 
         FEMALE = if_else(SEX==2, 1, 0), 
         NONWHITERACE = if_else(RACE==2, 1, 0), 
         EJFMETH = case_when(
           EJFMETH == 1 ~ "Radionuclide", 
           EJFMETH == 2 ~ "Angiography", 
           EJFMETH == 3 ~ "2-D Echo"))
```


```{r}
df2$EJFMETH <- factor(df2$EJFMETH, levels = c("Radionuclide", "Angiography", "2-D Echo"))
```



```{r}
df2 %>% 
  select(TRTMT, AGE, EJF_PER, CHFDUR, FEMALE, NONWHITERACE, EJFMETH, NSYM) %>% 
  tbl_summary(by = TRTMT, 
              label = c(AGE ~ "Age", 
                        EJF_PER ~ "Ejection fraction", 
                        FEMALE ~ "Female sex", 
                        CHFDUR ~ "Median duration of CHF", 
                        NONWHITERACE ~ "Nonwhite race", 
                        EJFMETH ~ "Method of assessing ejection fraction", 
                        NSYM ~ "No. of signs or symptoms of CHF"), 
              missing_text = "(Missing)") %>% 
  bold_labels() %>% 
  as_flex_table()
```

You can save as the RTF, PNG, and HTML format.

```{r}
table <- df2 %>% 
  select(TRTMT, AGE, EJF_PER, CHFDUR, FEMALE, NONWHITERACE, EJFMETH, NSYM) %>% 
  tbl_summary(by = TRTMT, 
              label = c(AGE ~ "Age", 
                        EJF_PER ~ "Ejection fraction", 
                        FEMALE ~ "Female sex", 
                        CHFDUR ~ "Median duration of CHF", 
                        NONWHITERACE ~ "Nonwhite race", 
                        EJFMETH ~ "Method of assessing ejection fraction", 
                        NSYM ~ "No. of signs or symptoms of CHF"), 
              missing_text = "(Missing)") %>% 
  bold_labels() %>% 
  as_gt()

gtsave(data = table, file = file.path(getwd(), "02_descriptive_stas_table.rtf"))
gtsave(data = table, file = file.path(getwd(), "02_descriptive_stas_table.png"))
gtsave(data = table, file = file.path(getwd(), "02_descriptive_stas_table.html"))
```
